In [1]:
# EDA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

sns.set(style="whitegrid")

# Machine Learning
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

### Carregar os dados

In [2]:
# Carregar os dados
df_leads = pd.read_csv('./datasets/leads_cleaned.csv')

In [3]:
# Mostrar as primeiras linhas do DataFrame
df_leads.head(10)

Lead Origin     Lead Source  Do Not Email  Do Not Call  \
0                      API      Olark Chat             0            0   
1                      API  Organic Search             0            0   
2  Landing Page Submission  Direct Traffic             0            0   
3  Landing Page Submission  Direct Traffic             0            0   
4  Landing Page Submission          Google             0            0   
5                      API      Olark Chat             0            0   
6  Landing Page Submission          Google             0            0   
7                      API      Olark Chat             0            0   
8  Landing Page Submission  Direct Traffic             0            0   
9                      API          Google             0            0   

   Converted  TotalVisits  Total Time Spent on Website  Page Views Per Visit  \
0          0          0.0                            0                   0.0   
1          0          5.0                          674                   2.5   
2          1          2.0                         1532                   2.0   
3          0          1.0                          305                   1.0   
4          1          2.0                         1428                   1.0   
5          0          0.0                            0                   0.0   
6          1          2.0                         1640                   2.0   
7          0          0.0                            0                   0.0   
8          0          2.0                           71                   2.0   
9          0          4.0                           58                   4.0   

             Last Activity  Search  Newspaper Article  X Education Forums  \
0  Page Visited on Website       0                  0                   0   
1             Email Opened       0                  0                   0   
2             Email Opened       0                  0                   0   
3              Unreachable       0                  0                   0   
4        Converted to Lead       0                  0                   0   
5  Olark Chat Conversation       0                  0                   0   
6             Email Opened       0                  0                   0   
7  Olark Chat Conversation       0                  0                   0   
8             Email Opened       0                  0                   0   
9             Email Opened       0                  0                   0   

   Newspaper  Digital Advertisement  Through Recommendations  \
0          0                      0                        0   
1          0                      0                        0   
2          0                      0                        0   
3          0                      0                        0   
4          0                      0                        0   
5          0                      0                        0   
6          0                      0                        0   
7          0                      0                        0   
8          0                      0                        0   
9          0                      0                        0   

   A free copy of Mastering The Interview Last Notable Activity  
0                                       0              Modified  
1                                       0          Email Opened  
2                                       1          Email Opened  
3                                       0              Modified  
4                                       0              Modified  
5                                       0              Modified  
6                                       0              Modified  
7                                       0              Modified  
8                                       1          Email Opened  
9                                       0          Email Opened

In [4]:
# Mostar as ultimas linhas do DataFrame
df_leads.tail(10)

Lead Origin     Lead Source  Do Not Email  Do Not Call  \
9064  Landing Page Submission          Google             0            0   
9065  Landing Page Submission          Google             0            0   
9066  Landing Page Submission  Direct Traffic             0            0   
9067                      API  Direct Traffic             0            0   
9068  Landing Page Submission  Direct Traffic             0            0   
9069  Landing Page Submission  Direct Traffic             1            0   
9070  Landing Page Submission  Direct Traffic             0            0   
9071  Landing Page Submission  Direct Traffic             1            0   
9072  Landing Page Submission          Google             0            0   
9073  Landing Page Submission  Direct Traffic             0            0   

      Converted  TotalVisits  Total Time Spent on Website  \
9064          0          2.0                          870   
9065          1          8.0                         1016   
9066          0          2.0                         1770   
9067          1         13.0                         1409   
9068          1          5.0                          210   
9069          1          8.0                         1845   
9070          0          2.0                          238   
9071          0          2.0                          199   
9072          1          3.0                          499   
9073          1          6.0                         1279   

      Page Views Per Visit      Last Activity  Search  Newspaper Article  \
9064                  2.00       Email Opened       0                  0   
9065                  4.00       Email Opened       0                  0   
9066                  2.00           SMS Sent       0                  0   
9067                  2.60           SMS Sent       0                  0   
9068                  2.50           SMS Sent       0                  0   
9069                  2.67  Email Marked Spam       0                  0   
9070                  2.00           SMS Sent       0                  0   
9071                  2.00           SMS Sent       0                  0   
9072                  3.00           SMS Sent       0                  0   
9073                  3.00           SMS Sent       0                  0   

      X Education Forums  Newspaper  Digital Advertisement  \
9064                   0          0                      0   
9065                   0          0                      0   
9066                   0          0                      0   
9067                   0          0                      0   
9068                   0          0                      0   
9069                   0          0                      0   
9070                   0          0                      0   
9071                   0          0                      0   
9072                   0          0                      0   
9073                   0          0                      0   

      Through Recommendations  A free copy of Mastering The Interview  \
9064                        0                                       0   
9065                        0                                       0   
9066                        0                                       1   
9067                        0                                       0   
9068                        0                                       0   
9069                        0                                       0   
9070                        0                                       1   
9071                        0                                       1   
9072                        0                                       0   
9073                        0                                       1   

     Last Notable Activity  
9064          Email Opened  
9065          Email Opened  
9066              SMS Sent  
9067              SMS Sent  
9068              Modified  
9069     Em

In [5]:
# Mostrar estrutura do DataFrame
df_leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9074 entries, 0 to 9073
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Lead Origin                             9074 non-null   object 
 1   Lead Source                             9074 non-null   object 
 2   Do Not Email                            9074 non-null   int64  
 3   Do Not Call                             9074 non-null   int64  
 4   Converted                               9074 non-null   int64  
 5   TotalVisits                             9074 non-null   float64
 6   Total Time Spent on Website             9074 non-null   int64  
 7   Page Views Per Visit                    9074 non-null   float64
 8   Last Activity                           9074 non-null   object 
 9   Search                                  9074 non-null   int64  
 10  Newspaper Article                       9074 non-null   int6

### Preparação dos dados

In [6]:
# Preparar os dados para o modelo
X = df_leads.drop(columns=['Converted'])
y = df_leads['Converted']

In [7]:
# Criar lista de colunas para a parte de interpretabilidade
numeric_features = X.select_dtypes(include=['number']).columns
categorical_features = X.select_dtypes(include=['object']).columns

In [8]:
# Usar o preprocessamento já salvo anteriormente
import joblib
preprocessor = joblib.load('./preprocessor_dataset_leads.pkl')

In [9]:
# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)


In [10]:
# Aplicar o pré-processamento
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [11]:
# Mostrar a estrutura do conjunto de treino
print(X_train.shape)
print(X_test.shape)

(7259, 68)
(1815, 68)


### Treinamento do modelo

In [12]:
# Criar o modelo de BoostingClassifier
boosting_model = AdaBoostClassifier(
    estimator=LogisticRegression(),
    n_estimators=50,
    learning_rate=1.0,
    random_state=51
    )

In [13]:
# Treinar o modelo
boosting_model.fit(X_train, y_train)

AdaBoostClassifier(estimator=LogisticRegression(), random_state=51)

### Avaliação do modelo

In [14]:
# Fazer predições no conjunto de teste
y_pred = boosting_model.predict(X_test)

In [15]:
# Metricas do modelo
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [16]:
# Mostrar as métricas de avaliação
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

Accuracy: 0.7857
Precision: 0.7004
Recall: 0.7328
F1 Score: 0.7163


In [17]:
# Mostrar a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)

fig = px.imshow(conf_matrix, labels=dict(x="Predição", y="Real", color="Contagem"),x=['Not Converted', 'Converted'], y=['Not Converted', 'Converted'], color_continuous_scale='Viridis')

fig.update_traces(text=conf_matrix, texttemplate="%{z}")
fig.update_layout(coloraxis_showscale=False)

fig.show()

In [18]:
# Calcular a importância das features
importances = np.mean([np.abs(estimator.coef_[0]) for estimator in boosting_model.estimators_], axis=0)

In [21]:
# Obter os nomes das features reais
feature_names = (numeric_features.tolist() + preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features).tolist())

In [24]:
# Criar um dataframe com as importâncias
df_feature_importances = pd.DataFrame({'Feature': feature_names, 'Importance': importances})

In [26]:
# Ordenar o dataframe pelas importâncias
df_feature_importances = df_feature_importances.sort_values(by='Importance', ascending=True)

In [27]:
# Plotar o grafico de importâncias

fig = px.bar(df_feature_importances, x='Importance', y='Feature', orientation='h', title='Importância das Features (Baseada nos coeficientes do absolutos)')
fig.update_layout(height=1280, width=1000, yaxis={'categoryorder': 'total ascending'} )

fig.show()

### Saídas do modelo

In [28]:
# Erros dos estimadores
boosting_model.estimator_errors_

array([0.37994214, 0.25903465, 0.44301389, 0.33267367, 0.43273034,
       0.42626923, 0.43217547, 0.48644275, 0.4268625 , 0.46478223,
       0.46065486, 0.46999515, 0.43488796, 0.48436183, 0.46258432,
       0.47685372, 0.48452293, 0.47781898, 0.47395167, 0.48928659,
       0.47750794, 0.48789657, 0.48545929, 0.48847906, 0.48047169,
       0.48643136, 0.49735856, 0.49632236, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [29]:
# Pesos dos estimadores
boosting_model.estimator_weights_

array([0.48979381, 1.05099201, 0.22893916, 0.69611714, 0.27072002,
       0.29708911, 0.27298076, 0.05424229, 0.29466371, 0.14110472,
       0.1577066 , 0.12016377, 0.26193558, 0.0625731 , 0.14994301,
       0.09265133, 0.06192807, 0.08878236, 0.10428774, 0.04286018,
       0.09002898, 0.04842316, 0.05817924, 0.04609193, 0.07815299,
       0.05428788, 0.01056587, 0.01471083, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [30]:
# Predizer a Probabilidade de Conversão
y_pred_proba = boosting_model.predict_proba(X_test)

In [31]:
# Visualizar Probabilidades
y_pred_proba

array([[0.28892438, 0.71107562],
       [0.55085138, 0.44914862],
       [0.55085138, 0.44914862],
       ...,
       [0.75407715, 0.24592285],
       [0.70374288, 0.29625712],
       [0.30284882, 0.69715118]], shape=(1815, 2))